"""The v2 surface: executor, taxonomy, evidence chains, certificate, router."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from friction.executor import build_plan, to_pytest_id


def test_pytest_id_mapping():
    assert to_pytest_id("tests.test_gate::test_x") == \
        "tests/test_gate.py::test_x"
    assert to_pytest_id("pkg.mod::Cls.method") == \
        "pkg/mod.py::Cls.method"
    assert to_pytest_id("test_core::test_helper") == "test_core.py::test_helper"
    assert to_pytest_id("no_separator") is None
    assert to_pytest_id("..traversal::x") is None       # never guess paths


def test_build_plan_always_ships_the_fallback():
    plan = build_plan(("tests.test_a::t1", "unmappable"))
    assert plan.selected_ids == ("tests/test_a.py::t1",)
    import sys
    assert plan.full_command == [sys.executable, "-m", "pytest"]


def test_run_command_dry_run(capsys, tmp_path, monkeypatch):
    """friction run without --exec prints both commands; runs nothing."""
    from friction import cli as C
    d = tmp_path / "r"; d.mkdir()
    (d / "core.py").write_text("def compute(x):\n    return x + 1\n")
    (d / "test_core.py").write_text(
        "from core import compute\n\ndef test_helper():\n"
        "    assert compute(1) == 2\n")
    code = C.main(["run", "--repo", str(d), "--changed", "core.py"])
    out = capsys.readouterr().out
    assert code in (0, 1)
    assert "python -m pytest test_core.py::test_helper" in out
    assert "fallback" in out


def test_run_exec_reports_pytests_own_exit(capsys, tmp_path):
    """--exec actually runs pytest and passes ITS exit code through (0 pass)."""
    from friction import cli as C
    d = tmp_path / "r2"; d.mkdir()
    (d / "core.py").write_text("def compute(x):\n    return x + 1\n")
    (d / "test_core.py").write_text(
        "from core import compute\n\ndef test_helper():\n"
        "    assert compute(1) == 2\n")
    code = C.main(["run", "--repo", str(d), "--changed", "core.py",
                   "--exec"])
    out = capsys.readouterr().out
    assert code == 0                      # the selected few pass
    assert "executed : exit 0" in out


def test_path_taxonomy_classes():
    from friction.triage import classify_path
    assert classify_path(".github/workflows/ci.yml") == "ci"
    assert classify_path("pytest.ini") == "test_config"
    assert classify_path("pnpm-lock.yaml") == "lockfile"
    assert classify_path("pyproject.toml") == "root_config"
    assert classify_path("README.md") is None


def test_evidence_chains_present(tmp_path, monkeypatch):
    """The walk now ships the change→test chain for selected tests."""
    import friction.triage as T
    mini = tmp_path / "m"; mini.mkdir()
    (mini / "core.py").write_text(
        "def compute(x):\n    return x + 1\n\ndef helper(x):\n"
        "    return compute(x)\n")
    (mini / "test_core.py").write_text(
        "from core import helper\n\ndef test_helper():\n"
        "    assert helper(1) == 2\n")

    def fake_gh(path, token=None):
        if "/files" in path:
            return [{"filename": "core.py", "status": "modified"}]
        raise AssertionError(path)

    def fake_clone(slug, dest, pr_number=None, branch=None):
        for f in mini.iterdir():
            (dest / f.name).write_text(f.read_text(), encoding="utf-8")

    monkeypatch.setattr(T, "_gh", fake_gh)
    monkeypatch.setattr(T, "_shallow_clone", fake_clone)
    r = T.triage("https://github.com/o/r/pull/3")
    assert r.gate is not None and r.gate.evidence
    chain = next(iter(r.gate.evidence.values()))
    assert chain[0].startswith("core") and chain[-1].startswith("test_core")
    md = T.render_markdown(r)
    assert "chain:" in md and "snapshot:" in md


def test_generated_file_provenance_warning(tmp_path, monkeypatch):
    import friction.triage as T
    mini = tmp_path / "g"; mini.mkdir()
    (mini / "gen.py").write_text(
        "# auto-generated by the schema compiler — do not edit\n"
        "def generated_thing():\n    return 1\n")
    (mini / "test_gen.py").write_text(
        "from gen import generated_thing\n\ndef test_gen():\n"
        "    assert generated_thing()\n")

    def fake_gh(path, token=None):
        if "/files" in path:
            return [{"filename": "gen.py", "status": "modified"}]
        raise AssertionError(path)

    def fake_clone(slug, dest, pr_number=None, branch=None):
        for f in mini.iterdir():
            (dest / f.name).write_text(f.read_text(), encoding="utf-8")

    monkeypatch.setattr(T, "_gh", fake_gh)
    monkeypatch.setattr(T, "_shallow_clone", fake_clone)
    r = T.triage("https://github.com/o/r/pull/4")
    assert "machine-generated" in r.gate.prior_note


def test_verify_certificate(capsys, tmp_path):
    from friction import cli as C
    cert = tmp_path / "cert.json"
    code = C.main(["verify", "--certificate", str(cert)])
    capsys.readouterr()
    assert code == 0
    d = json.loads(cert.read_text())
    assert d["figures"]["arm_b"] == "24/44"
    assert len(d["gate_results_sha256"]) == 64


def test_mcp_router():
    from friction.mcp_server import route
    assert json.loads(route("which edges are confirmed?"))["route"] == \
        "graph_query"
    assert json.loads(route("is it safe to skip tests?"))["route"] == \
        "gate_check"
    assert json.loads(route("what is the weather"))["route"] == "abstain"
